### ISSUE TITLE
price is blacked out

### ISSUE THREAD

**Issue by mikebelson** [philippe-git/ethereum-gas-prices-browser-extension#15]
I have had this extension for a while, and then today the gas price is blacked out. it was never like that before. what's wrong
![IMG_3665](https://user-images.githubusercontent.com/106509744/170928439-3cbde931-66cc-42f8-9ce1-6d9a770af05e.jpg)
?

**Comment by mikebelson** [comment]
still blacked out

**Comment by chanceyliu** [comment]
me too

**Comment by philippe-git** [comment]
This seems to be an issue with the latest Chrome update, other extensions (on the screenshot, Gmail Checker) are impacted as well; the issue seems to be that Chrome doesn't adapt the badge's text color in accordance to its background color anymore, which makes black text on a dark background unreadable:

<img width="67" alt="image" src="https://user-images.githubusercontent.com/2307365/171601995-197e6011-b9ba-48fd-bab7-c190f887fd7f.png">

This is clearly a browser issue, but in order to make the extension work again without waiting for a new browser release, I've pushed an updated version (v1.3.3) with a light background color:

<img width="41" alt="image" src="https://user-images.githubusercontent.com/2307365/171612388-07ebd1aa-5124-40b0-96ec-cb7a6b71d0a3.png">

A new extension version typically takes 1-2 days to be reviewed on the Chrome Store, and then something like a day for your browser to automatically download the new extension version. In the meantime, hope you don't mind clicking the extension badge to see gas prices in the dropdown – also feel free to install the new version manually without waiting for the store by building it yourself from this repo!

Closing this issue as it's now only a matter of time before the workaround reaches your respective browsers!
