### ISSUE TITLE
Stopped working last night on Google Chrome

### ISSUE THREAD

**Issue by bbdefender1** [philippe-git/ethereum-gas-prices-browser-extension#7]
Last night the extension stopped working for me.  The gwei number just froze and wouldn't update.  I have tried rebooting and uninstalling/reinstalling etc but it won't start working again.  Now I have uninstalled and reinstalled instead of a number it is just displaying three dots like ...

I am using the extension on Google Chrome (automatic updates enabled)/Windows 7.  

Thank you for any help.  This is a very useful and good extension so would love for it to be working again
![ethgasprices](https://user-images.githubusercontent.com/98122917/150411790-49980749-c9a7-4472-9931-6eff3b77134a.jpg)
.

**Comment by ruslus86** [comment]
I have the same issue. When I press separately on 3 websites they work but extension itself is not working.

**Comment by aiprat** [comment]
Same here. Stopped working few days ago. No gas updates.

**Comment by philippe-git** [comment]
Sorry everyone, this is because this extension used to rely on a backend that proxied requests to the various gas services it uses to optimize for speed and reliability, however the extension has gotten so popular that server costs to run this proxy had gotten to a level that I couldn't justify anymore for a free extension.

Hence I've shut down the proxy server and modified the extension to query the gas services directly from each user's browser. There may be some things to polish at first with this new approach (esp. with rates limits and whatnot), but it's an approach that works very well too.

The new version (1.3.0) is functional and was published several days ago already, unfortunately the Chrome store was quite slow to publish it, *and* the browser's automatic extension update process takes its sweet time too :x 

If your extension still hasn't updated to the latest version (i.e. if it doesn't work, it didn't), you can simply uninstall then reinstall the extension, and you'll have the latest one, fully working again (minus the few quirks I'll be fixing promptly).

Sorry for the downtime! This issue is resolved, but let's leave it open for a while so that people still stuck on an older version can know what to do!
